name: 🐛 Bug Report
description: Reportar um bug ou problema no sistema
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug! Por favor, preencha as informações abaixo para nos ajudar a resolver o problema.

  - type: textarea
    id: description
    attributes:
      label: 📝 Descrição do Bug
      description: Descrição clara e concisa do que está acontecendo
      placeholder: Descreva o bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Passos para Reproduzir
      description: Passos para reproduzir o comportamento
      placeholder: |
        1. Vá para '...'
        2. Clique em '...'
        3. Role para baixo até '...'
        4. Veja o erro
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Comportamento Esperado
      description: Descrição clara do que você esperava que acontecesse
      placeholder: Eu esperava que...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots
      description: Se aplicável, adicione screenshots para ajudar a explicar o problema
      placeholder: Cole ou arraste imagens aqui...

  - type: dropdown
    id: module
    attributes:
      label: 📦 Módulo Afetado
      description: Qual módulo está apresentando o problema?
      options:
        - Painéis
        - Projetos
        - Relatórios
        - Cabinetes
        - Agendamento
        - Test Cards
        - Técnicos
        - Autenticação
        - UI/UX
        - Outro
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🚨 Prioridade
      description: Qual a severidade do bug?
      options:
        - 🔴 Crítico - Sistema não funciona
        - 🟡 Alto - Funcionalidade principal afetada
        - 🟢 Médio - Funcionalidade secundária afetada
        - 🔵 Baixo - Problema cosmético
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: 🌐 Browser
      description: Qual browser você estava usando?
      placeholder: Chrome 91, Firefox 89, Safari 14, etc.

  - type: input
    id: os
    attributes:
      label: 💻 Sistema Operacional
      description: Qual sistema operacional você está usando?
      placeholder: Windows 11, macOS 12, Ubuntu 20.04, etc.

  - type: textarea
    id: additional
    attributes:
      label: ℹ️ Informações Adicionais
      description: Qualquer outra informação relevante sobre o problema
      placeholder: Contexto adicional...
